#ifndef MYSMSGIDS_H_
#define MYSMSGIDS_H_

#include "MessageIdentifiers.h"

enum MyMsgIDs
{
	ID_WELCOME = ID_USER_PACKET_ENUM,
	ID_NEWSHIP,
	ID_LOSTSHIP,
	ID_INITIALPOS,
	ID_MOVEMENT,
	ID_COLLIDE,
	// Lab 13 Task 7 : Add new messages
	ID_NEWMISSILE,
	ID_UPDATEMISSILE,
	ID_NEWASTEROID,
	ID_UPDATEASTEROID,
	ID_SPAWNASTEROID,
	ID_SPAWNMINIASTEROID,
	ID_DELETEASTEOIRD,
	ID_SPLIT_ASTEROID,
	ID_SPAWNBOMB,
	ID_UPDATE_BOMB,
	ID_CREATE_EXPLOSION,
	ID_UPDATE_EXPLOSION,
	ID_DEBUG,
};

#endif